- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/BetaVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/ExponentialVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/GammaVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/GaussianVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/LogisticVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/SmoothUniformTest.java
This PR locks down the infer from samples such that they always return the same result.
> Use seeded random in infer from samples tests

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/CastDoubleVertex.java
This PR relaxes the requirements for DoubleVertex casting. Any Number can now be casted to an DoubleVertex. However, this operation is non-differentiable and throws an exception is a dual number calculation is requested.
> Allow casting of any Number to a DoubleVertex

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
The current error message experienced when trying to sample with MCMC from a graph that does not have any probabilistic vertices is a cryptic enigma wrapped in a mystery: `Exception in thread "main" java.lang.ArithmeticException: / by zero`.
Let's make this a bit more clear.
> Improve error message when using MCMC

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ArcTan2Vertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/PowerVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/BetaVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ChiSquaredVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ExponentialVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/GammaVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/GaussianVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/InverseGammaVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/LaplaceVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/LogisticVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/SmoothUniformVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/TriangularVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/UniformVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/PoissonVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertex.java
Alex Sparrow raised the point that there is a large amount of inconsistency across the constructors of Vertices.
Some allow you to pass in only `DoubleVertex's` as arguments, some allow double's, some allow a mix of the two and some allow you to pass in a random and some create a random for you. There's quite a large mix. This is largely my fault as I've been creating them without giving them much thought. 
This seeks to generalise this across the board and hopefully give new Vertices some structure to follow.
> Generalise Constructors

- keanu-project/build.gradle
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/SimulatedAnnealing.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/particleFiltering/ParticleFilter.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/GradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/NonGradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Beta.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Exponential.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Gamma.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Laplace.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Logistic.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/SmoothUniformDistribution.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Triangular.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Uniform.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/discrete/Poisson.java
- keanu-project/src/main/java/io/improbable/keanu/kotlin/ArithmeticDouble.kt
- keanu-project/src/main/java/io/improbable/keanu/network/BayesNet.java
- keanu-project/src/main/java/io/improbable/keanu/plating/PlateBuilder.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/Constant.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/Vertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/NumericalEqualsVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/LogProbGradient.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/GammaVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/FuzzyCastToIntegerVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertex.java
There are several javadoc warnings that are printed on build. This PR addresses all of the warnings and adds some build config to break the build on a javadoc warning.
> Fix javadoc warnings

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/CastDoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/ConstantDoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/AdditionVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ArcTan2Vertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/DifferenceVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/DivisionVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/DoubleBinaryOpLambda.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MultiplicationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/PowerVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/DoubleReduceVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/AbsVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcCosVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcSinVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcTanVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CeilVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CosVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/DoubleUnaryOpLambda.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ExpVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/FloorVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/LogVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SinVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TanVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ProbabilisticDouble.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/DualNumberPropagationTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/LazyEvalPropagationTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/TestGraphGenerator.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/VertexValuePropagationTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DoubleVertexTest.java
A performance fix for Dual Numbers. 
Ensures that when calculating Dual Numbers, a vertex's Dual Number is never calculated more than once.
> Dual Number performance fix

- keanu-examples/coalMiningDisasters/settings.gradle
- keanu-examples/starter/build.gradle
Add required settings for running coal mining example independently  outside of top level Keanu build.
This PR enables a user to change directory into the coal mining example and `gradle build` just the example. It also allows them to use `gradle run` in the coal mining example and the starter project to automatically run their respective `main(String[] args)` methods.
> Run examples independently of parent build

- .editorconfig
This PR adds a .editorconfig file that allows other code editors to format code as expected in the Keanu Repo. More about editor config [here](http://editorconfig.org/)
> Add default Intellij editor config

- .travis.yml
Due to Travis security concerns we cannot run `sonar-scanner` on PR's sourced from external (forked) repo's.
This allows the build to pass for PR's raised from external repo's by not running `sonar-scanner`.
Tested on Justin's external PR: https://travis-ci.org/improbable-research/keanu/builds/378740910
> Run Sonar on Internal PR's

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/Hamiltonian.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NUTS.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/SimulatedAnnealing.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/initialconditions/MultiModeDiscovery.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/tensor/TensorHamiltonian.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/tensor/TensorNUTS.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/sampling/Prior.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/sampling/RejectionSampler.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/GradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/NonGradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/tensor/TensorFitnessFunction.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/tensor/TensorFitnessFunctionWithGradient.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/tensor/TensorGradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/tensor/TensorNonGradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/network/BayesianNetwork.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbltensor/nonprobabilistic/diff/TensorPartialDerivatives.java
- keanu-project/src/test/java/io/improbable/keanu/e2e/regression/LinearRegression.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbltensor/probabilistic/ProbabilisticDoubleTensorContract.java
This PR fixes a bug with tensor autodiff. It also adds a `onGradientCalculation(...)` and a `onFitnessCalculation(...)` for easy debug of optimizer convergence checking.
> Fix autodiff bug and add debug helpers for optimizer

- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
Remove the Sigmoid object creation from math commons and just use the function that it represents.
> Use sigmoid function instead of apache math commons object

- keanu-project/src/main/java/io/improbable/keanu/vertices/bool/BoolVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/IntegerVertex.java
It's a pain to do vertex.getValue().getValue(1,2,3), so this adds a convenience method for this.
> Added getValue short hand for getValue().getValue(x,y)

- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/NumericalEqualsVertexTest.java
This PR cleans up some tech debt. Some basic tests are added and a bug fix with DoubleTensor.absInPlace().
> Add testing for numerical equals vertex

- keanu-project/src/main/java/io/improbable/keanu/algorithms/particlefiltering/ParticleFilter.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/sampling/Prior.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/sampling/RejectionSampler.java
- keanu-project/src/main/java/io/improbable/keanu/network/BayesianNetwork.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/Vertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/bool/probabilistic/ProbabilisticBool.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ProbabilisticDouble.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/probabilistic/Probabilistic.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/ProbabilisticInteger.java
This PR allows a user to not care about a random number generator and instead use the default one available. IF the user wants to make the run deterministic, they can set the default seed by `KeanuRandom.setDefaultRandomSeed(some_seed_value);`
> Random not required

- build.gradle
- keanu-docs/code/build.gradle
- keanu-examples/coalMiningDisasters/build.gradle
- keanu-examples/starter/build.gradle
- keanu-project/build.gradle
https://github.com/palantir/gradle-git-version
Now when you do a `./gradlew build` it creates artifacts with names like `keanu-c06889c.jar`
It should create names like `keanu-v0.0.10-1-gc06889c.jar` - the reason it isn't (at least on this feature branch) is to do with the `--first-parent` option in [`git describe`](https://git-scm.com/docs/git-describe): "Follow only the first parent commit upon seeing a merge commit". Perhaps the behaviour will be different on the develop and/or master branches.
> Added git-version plugin

- keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/bool/BoolVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/IntegerVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/bool/BoolVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DoubleVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/DoubleBinaryOpLambdaTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/DoubleUnaryOpLambdaTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/IntegerVertexTest.java
Previously, when you observed/setValue/setAndCascade a primitive or array then it would NOT reshape the vertex. This has been confusing to users (and me) and I propose we change the behaviour to be such that anything you set or observe is exactly reflected in the vertex. For example, setting or observing a scalar value would make the shape of the vertex scalar and if you observe an array then the vertex would would be reshaped as a vector.
> Change behaviour to reshape on setValue and observe

- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShapeValidation.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/bool/BooleanTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/IntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/ScalarIntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/multiple/BoolConcatenationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ConcatenationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ReduceVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/operators/multiple/IntegerConcatenationVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/multiple/BoolConcatenationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ConcatenationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ReduceVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/operators/multiple/IntegerConcatenationVertexTest.java
Tensor vertex concatenation for double / integer and boolean. Also renamed DoubleReduceVertex to ReduceVertex to match the naming convention.
A ticket has been added to the backlog to finish the Generic Concatenation as this is a bit of a chunk of work in itself.
> Vertex concatenation

- keanu-project/src/main/java/io/improbable/keanu/network/BayesianNetwork.java
- keanu-project/src/test/java/io/improbable/keanu/network/BayesianNetworkTest.java
There was a bug whereby the `BayesianNetwork` stores the latent and observed variables on construction only, which means if you observe a non-probabilistic vertex later it won't be added to this list.
The solution is to calculate the latent and observed variables dynamically. Of course this has an impact on performance in time and space, but we agreed that it's more important at this stage to be correct and to optimise later.
If we want to optimise later, we'd need some kind of callback mechanism whereby a `Vertex` notifies a `BayesianNetwork` when it gets observed.
> youCanObserveANonProbabilisticVariableAfterCreatingTheNetwork

- keanu-examples/coalMiningDisasters/src/main/java/com/example/coal/Model.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Exponential.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/dual/Diffs.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ExponentialVertex.java
- keanu-project/src/test/java/io/improbable/keanu/distributions/gradient/Exponential.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/ExponentialVertexTest.java
The location of a distribution can controlled by just adding an offset. This PR removes the location hyper parameter in the ExponentialVertex that has been confusing people. Mathematically the location is now at 0.0.
> Remove location from exponential distribution

- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TakeVertexTest.java
This PR fixes a bug that was previously not caught in out matrix multiply tests. Tests have been added to catch it now and a function `permute` has been added to the DoubleTensor in order to make the bug fix elegant. This permute is similar to moveaxis in numpy https://docs.scipy.org/doc/numpy/reference/generated/numpy.moveaxis.html
> Fix bug in forward mode matrix multiply auto differentiation

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NUTS.java
When calling `NUTS.getPosteriorSamples` with a specified `KeanuRandom` instance as the final input parameter (as is done in all the NUTS tests), the second parameter is of type `List<? extends Vertex>`. When calling it without that final input, the second parameter is of type `List<DoubleVertex>`. They should be the same.
> NUTS interface consistency

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfCauchyVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfCauchyVertexTest.java
Food for thought, subclassing CauchyVertex might be the easiest way to implement a HalfCauchyVertex.
I may be oversimplifying things, but I believe a half-Cauchy distribution is just a Cauchy distribution with location zero with its left half dropped and the rest scaled up by two. (I think logPdf doesn't care about scaling factors (biases in log space) so we don't even need to do that step.) And the gradient is twice as steep as it would be for the CauchyVertex. This gradient calculation implementation doesn't care if the value is less than zero, so it is not really an accurate gradient for those values, but since they have probability density zero anyway does it matter?
>  Added HalfCauchyVertex: a subclass of CauchyVertex

- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Uniform.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/discrete/UniformInt.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/UniformVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertexTest.java
Will use it for computing KL divergence.
Also added a fix for #197.
> Extract distributions/discrete/UniformInt from UniformIntVertex.

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/SamplingAlgorithm.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastingsTest.java
Fix Issue with Metropolis Hastings algorithm not generating samples correctly (we always returned the same value) if Downsampling not used when streaming.
Also includes a small fix to the Metropolis Hastings tests to make it more reliable (it was randomly failing for me).
> Fix for Issue 190

- keanu-project/src/main/java/io/improbable/keanu/tensor/bool/BooleanTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/IntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/bool/BoolVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/IntegerVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/bool/BoolVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DoubleVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/IntegerVertexTest.java
Adds reshape to `Double`, `Integer` and `Bool` vertices.
Also adds an `(int...)` constructor to `ones` in `IntegerTensor` to keep it consistent.
Also adds a `trues` and `falses` constructor for `BooleanTensor`
> Add reshape to vertices

- keanu-project/src/main/java/io/improbable/keanu/tensor/INDArrayShim.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
- Fixes a bug in the broadcast operations when operating on two tensors. Eg, multiplying a 2x2 by a 2x2x2x2 produced incorrect numbers and was different if you were doing A x B or B x A. The behaviour is now representative of numpy.
- Fixes a bug in TensorShape prepend with 1's
- Due to the behaviour of ND4J it's impossible to perform a broadcast in place on a tensor that has to increase in size. You could do an `inPlace` if multiplying a 2x2x2x2 by a 2x2, but not a 2x2 by a 2x2x2x2. To avoid confusing behaviour I've made it so that `inPlace` on a broadcast returns a duplicate. `There's no in place unless the tensors match shape`.
- Fixed `DoubleIfVertex` to use the new broadcast. It was using the previously broken broadcast to apply a mask in a pretty cheeky way 
It's impossible in …
> Fix broadcast ops

- keanu-project/src/test/java/io/improbable/keanu/e2e/regression/LinearRegression.java
Looks like this was missed when other tests in this class were changed to use log.info.
> Found debugging print statement

- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
This PR adds a split that is nice and will be required by reverse mode autodiff for concat. 
From the JavaDoc:
```
/**
* @param dimension      the dimension to split on
* @param splitAtIndices the indices that the dimension to split on should be split on
* @return pieces of the tensor split in the order specified by splitAtIndices. To get
* pieces that encompasses the entire tensor, the last index in the splitAtIndices must
* be the length of the dimension being split on.
* <p>
* e.g A =
* [
* 1, 2, 3, 4, 5, 6
* 7, 8, 9, 1, 2, 3
* ]
* <p>
* A.split(0, [1]) gives List([1, 2, 3, 4, 5, 6])
* A.split(0, [1, 2] gives List([1, 2, 3, 4, 5, 6], [7, 8, 9, 1, 2, 3]
* <p>
* A.split(1, [1, 3, 6]) gives
* List(
* [1, [2, 3  , [4, 5, 6,
* 7]   8, 9]    1, 2, 3]
* )
*/
```
This is only for DoubleTensor …
> Add split for double tensors

- keanu-project/src/main/java/io/improbable/keanu/vertices/VertexId.java
When debugging it's a massive pain to access things if I don't have access to a vertex as I'm unable to create a `VertexID` on the fly. This let's you make a `VertexID`.
> Expose vertex id

- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MultiplicationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ConcatenationVertex.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ConcatenationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertexTest.java
This PR:
- adds concat to the list of supported reverse mode ops
- fixes an issue in reverse mode element wise multiply that multiplies along the wrong dimensions
> Reverse mode Autodiff for concat

- keanu-docs/code/src/main/java/io/improbable/docs/WetGrass.java
- keanu-examples/coalMiningDisasters/src/main/java/com/example/coal/Model.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NetworkSamplesGenerator.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/Optimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/gradient/GradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/nongradient/NonGradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/util/ProgressBar.java
- keanu-project/src/main/java/io/improbable/keanu/util/ProgressUpdate.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastingsTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/NetworkSamplesGeneratorTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/variational/optimizer/OptimizerTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/variational/optimizer/gradient/GradientOptimizerTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/variational/optimizer/nongradient/NonGradientOptimizerTest.java
- keanu-project/src/test/java/io/improbable/keanu/e2e/lorenz/LorenzTest.java
- keanu-project/src/test/java/io/improbable/keanu/util/ProgressBarTest.java
This PR introduces the first stab at a progress bar when running inference. The progress bar is handled by a daemon thread that writes to std out by default but can be configured and also disabled.
Generating samples (not streaming them)
Streaming samples
Optimizer progress
> Progress bar

- keanu-project/src/test/java/io/improbable/keanu/util/csv/pojo/byrow/ObjectParserWithPublicFieldTest.java
- keanu-project/src/test/java/io/improbable/keanu/util/csv/pojo/byrow/ObjectParserWithSetterMethodTest.java
This class overrides equals(Object), but does not override hashCode(), and inherits the implementation of hashCode() from java.lang.Object (which returns the identity hash code, an arbitrary value assigned to the object by the VM).  Therefore, the class is very likely to violate the invariant that equal objects must have equal hashcodes.
> class overrides equals(Object), but does not override hashCode()

- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/nongradient/FitnessFunction.java
- keanu-project/src/main/java/io/improbable/keanu/network/BayesianNetwork.java
This code checks to see if a floating point value is equal to the special Not A Number value (e.g., if (x == Double.NaN)). However, because of the special semantics of NaN, no value is equal to Nan, including NaN. Thus, x == Double.NaN always evaluates to false. To check to see if a value contained in x is the special Not A Number value, use Double.isNaN(x) (or Float.isNaN(x) if x is floating point precision).
> Doomed test for equality to NaN

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ChiSquaredVertex.java
Because we don't pass tensors to other vertex constructors?
> Pass IntegerVertex to ChiSquaredVertex instead of IntegerTensor

- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Beta.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/ChiSquared.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Dirichlet.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Gamma.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/InverseGamma.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/StudentT.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/discrete/Binomial.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/discrete/Multinomial.java
- keanu-project/src/main/java/io/improbable/keanu/distributions/discrete/Poisson.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/probabilistic/BinomialVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/probabilistic/PoissonVertexTest.java
In order to convert our LogProbs to a graph we need to use common (and supported) ops. In many of our LogProbs we don't use gamma when we could and in some cases where we do use gamma we do gamma and then log, which is the logGamma. This PR uses logGamma in LogProb where it can in preparation for making LogProb return a graph.
> Use logGamma in logProb

- keanu-examples/bayesianMethodsForHackers/src/main/java/examples/ChallengerDisaster.java
- keanu-examples/bayesianMethodsForHackers/src/main/java/examples/TextMessaging.java
- keanu-examples/bayesianMethodsForHackers/src/test/java/examples/ChallengerDisasterTest.java
- keanu-examples/bayesianMethodsForHackers/src/test/java/examples/TextMessagingTest.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/Vertex.java
The tests in #98 were failing in non-obvious ways. After digging into it and talking to @gordoncaleb, we determined that the proposal distribution for the Metropolis Hastings sampler (which was just the prior) was too wide, and made bad proposals, resulting in bad samples.
As the API for making a new proposal distribution is pretty clunky, this just changes the priors so that the proposal distribution is more appropriate.
> Fix failing tests for Bayesian Methods for Hackers

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/LogGammaVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/TensorTestOperations.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/LogGammaVertexTest.java
Log Gamma is a commonly used function in our distribution pdfs. In order to describe the pdf as a graph we need a vertex can be used for the operation.
> Add log gamma vertex with forward and reverse autodiff

- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/probabilistic/discrete/CategoricalVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/generic/probabilistic/discrete/CategoricalVertexTest.java
Fixes #185 by adding the ability to create a categorical vertex directly from a Dirichlet vertex. This means that the values of the Dirichlet vertex will become the probabilities for the values of the categorical vertex.
Tests have been added verifying the basic behaviour, that sampling from the resultant categorical vertex matches the probabilities from the input Dirichlet. 
Initial implementation by @johannespetrat, I simply tweaked and added tests
> Add ability to create categorical vertex of Dirichlet vertex

- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShapeValidation.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/MatrixDeterminantVertex.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/TensorShapeValidationTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DifferentiatorTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/TensorTestOperations.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/AdditionVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ConcatenationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/DivisionVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MaxVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MinVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/SliceVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcCosVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcSinVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcTanVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CosVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ExpVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/LogGammaVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/LogVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/MatrixDeterminantVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/MatrixInverseVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ReshapeVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SigmoidVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SinVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SumVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TakeVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TanVertexTest.java
This PR adds support for a determinant vertex. It takes a vertex shaped like a matrix as input, and outputs a scalar determinant.
Reverse auto diff has been implemented on this vertex as well. It's slightly problematic as it involves the inverse of our input matrix, which fails when the determinant is 0 (despite the gradient being well-defined at that point). This seems to be the expected way to perform such a calculation, and none of the literature even addresses this as a problem. @gordoncaleb and I couldn't think of a case where this would be a problem, and I added some random testing to verify this at least in a small case.
Forward differentiation has not been implemented.
> Add determinant vertex

- keanu-project/src/main/java/io/improbable/keanu/tensor/NumberTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShapeValidation.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/ScalarIntegerTensor.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/TensorMatchers.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/intgr/ScalarIntegerTensorTest.java
This PR adds a function to number tensors, `argMax`, that returns the indices of maximum values in a tensor. It's been adopted to follow the semantics of numpy's argmax method, which takes a single `axis` argument as opposed to an array of `dimensions`. It took me a while to grok how this method worked, so I tried to document it to help others a little more.
Shaping is a little strange with these semantics - the returned tensor can be rank 1 if the input was rank 2. Let me know if that's a problem and what we might want to do instead.
> Add argMax function to tensors

- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ConcatenationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SumVertex.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ConcatenationVertexTest.java
Previously we were splitting on the accidentally correct dimension in our tests. For higher rank tensors this fails.
> Fix bug in concat reverse mode autodiff

- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/Optimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/gradient/GradientOptimizer.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/nongradient/NonGradientOptimizer.java
This PR adds some documentation to detail the underlying methods behind the gradient and non-gradient optimizers. It also adds clarification on how the fitness and gradient evaluation callbacks work and how fitness is evaluated as probability of observed vertices.
> Add documentation to optimizers

- keanu-project/src/test/java/io/improbable/keanu/vertices/SamplableWithShapeTest.java
Placeholder no longer exists - updating a test that calls it
> Remove placeholder

- docs/src/test/java/io/improbable/snippet/Tensors.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/IntegerTensor.java
Made it to fix some python tests, but no longer needed.
> Remove IntegerTensor constructor that takes long values

- build.gradle
- codegen/build.gradle
- codegen/src/main/java/io/improbable/keanu/codegen/python/DocString.java
- codegen/src/main/java/io/improbable/keanu/codegen/python/KeanuProjectDoclet.java
- codegen/src/main/java/io/improbable/keanu/codegen/python/ParamStringProcessor.java
- codegen/src/main/java/io/improbable/keanu/codegen/python/Runner.java
- codegen/src/main/java/io/improbable/keanu/codegen/python/VertexProcessor.java
- codegen/src/main/resources/generated.py.ftl
- codegen/src/test/java/io/improbable/keanu/codegen/python/ParamStringProcessorTest.java
- keanu-python/keanu/vertex/generated.py
This PR introduces a feature to allow python constructors to pull in JavaDoc strings from their respective Java constructors. 
This is included as a gradle task that is run whenever `codegen:codegen` is run which is the existing way of generating python code.
What is not covered: 
- Python docs in hand written code
- Actually creation of python docs using e.g. Sphinx
- Any sort of generated python code that isn't a constructor
> Generate python constructor docs from JavaDoc strings

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/Hamiltonian.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/HamiltonianSampler.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/HamiltonianTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/MCMCTestDistributions.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/NUTSTest.java
- keanu-python/keanu/algorithm/__init__.py
- keanu-python/keanu/algorithm/sampling.py
- keanu-python/keanu/keanu_random.py
- keanu-python/keanu/sampling.py
- keanu-python/tests/test_gradient_optimization.py
- keanu-python/tests/test_non_gradient_optimization.py
- keanu-python/tests/test_sampling.py
- Refactor Hamiltonian to use the `Sampler` interface. 
- Allows users to create a generator for reading samples from a java stream
Works by turning the java stream into an iterator and then calling `next` on that each time the user calls `next` on the python generator
> Python streaming samples

- keanu-python/build.gradle
As the generated python doesn't conform to the style `formatApply` always changes them and thus always makes the files dirty. Put an exemption in for these files until they are made to meet the style.
> Python: Exclude generated paths on formatApply

- keanu-project/src/test/java/io/improbable/keanu/util/dot/DotSaverTest.java
As @gordoncaleb pointed out, using relative paths when reading in resource files might fail when tests are run from IDEs, as their test run location can be configured to a different place. Therefore I've changed file loading to obtain files from the loaded resources.
> Change the way DOT test resource files are read in

- codegen/build.gradle
This was causing the problem where `error: package com.google.protobuf does not exist` was reported from the `codegen` project.
The task `saveJavadocStringsToFile` analysed the source. However, it would generate warnings whenever an unknown dependency was encountered. The dependencies on the `keanu-project` classpath were not being correctly included in this task. The warnings were capped to 100, therefore only showing the protobuf issues.
- Stop processing generated and test sources. These are not used in the docs, so no need to process. Removes the need for including the compile classpath.
- Set the classpath for javadoc task to the runtime classpath of `keanu-project`.
- Include the compile class path of `keanu-project` in order to support Lombok.
> Codegen javadoc to json classpath

- keanu-project/build.gradle
Just a little change because the python classpath was getting populated with multiple versions of the `keanu` jar which was a bad thing.
> added a task to delete the python classpath before populating it

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NUTSSampler.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/HamiltonianTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/MCMCTestDistributions.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/NUTSTest.java
We are converting a potentially very negative value from log space into normal space. This can cause it to go to zero and wreck the algorithm. This PR keeps the number in log space and therefore avoids the going to zero problem.
> Numeric stability NUTS bug

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NUTS.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfCauchyVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfGaussianVertex.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/NUTSTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfCauchyVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfGaussianVertexTest.java
NUTS has an algorithm to find a good value of the `stepsize` before it begins sampling. The way this algorithm works is by continually increasing it, taking a leapfrog and measuring the delta in log likelihood until it goes under some threshold. We were not resetting the value of the vertices to their initial value after running this algorithm to find a good starting size, meaning it was left in the state that produced the low likelihood. In the case of vertices with bounds (`half_gaussian`, `half_cauchy`) this low likelihood area happened to be a negative value.
This PR resets the value of the vertices to their starting value after finding a good value for the stepsize.
This PR also adds boundary checks for `dLogProb` for `halfGaussian` and `halfCauchy` and returns zero if it's invalid, …
> Out of bounds sampling fix

- docs/index.md
Currently the index page displays "https://improbable-research.github.io/keanu/" as the title. Changed this to "Keanu Docs".
> Add title to index.md

- docs/bin/snippet_writer.py
- docs/current_docs/autocorrelation.md
- docs/current_docs/data-io.md
- docs/current_docs/getting-started.md
- docs/current_docs/inference-map.md
- docs/current_docs/inference-posterior-sampling.md
- docs/current_docs/lorenz-example.md
- docs/current_docs/overview.md
- docs/current_docs/particle-filter.md
- docs/current_docs/plates.md
- docs/current_docs/save-and-load.md
- docs/current_docs/tensors.md
- docs/current_docs/thermometer-example.md
- docs/src/test/java/io/improbable/snippet/AutocorrelationExample.java
- docs/src/test/java/io/improbable/snippet/CsvOperations.java
- docs/src/test/java/io/improbable/snippet/DescribingTheModel.java
- docs/src/test/java/io/improbable/snippet/Inference.java
- docs/src/test/java/io/improbable/snippet/Lorenz.kt
- docs/src/test/java/io/improbable/snippet/OptimizerExample.java
- docs/src/test/java/io/improbable/snippet/Overview.java
- docs/src/test/java/io/improbable/snippet/ParticleFilterExample.java
- docs/src/test/java/io/improbable/snippet/PlatesExample.java
- docs/src/test/java/io/improbable/snippet/SaveLoadExamples.java
- docs/src/test/java/io/improbable/snippet/SelectVertexExample.java
- docs/src/test/java/io/improbable/snippet/SimpleLinearRegressionExample.java
- docs/src/test/java/io/improbable/snippet/Tensors.java
- docs/src/test/java/io/improbable/snippet/WetGrass.java
`snippet_writer.py` is a script we use for extracting snippets out of Java examples for the docs. Previously it did a straight copy from the source file and therefore included any leading whitespace the block of code had in the snippet. This required either poorly formatting the source files or modifying the generated snippet so that it formatted correctly on the shiny docs.
- `snippet_writer.py` modified to remove leading whitespace from the block
- Existing Java source code reformatted using IntelliJ formatter
- Generated snippets updated with this formatting.
Note: commit 46550fc is where the generated snippets are updated with IntelliJ formatting so it may be easier to initially review without the diff of this commit.
> Snippet writer removes leading whitespace

- docs/bin/snippet_writer.py
- docs/build.gradle
- docs/settings.gradle
Makes sure `current_docs` is updated during build.
- Removed a redundant `settings.gradle`.
- Was stopping any tasks completing successfully when run from the `docs` directory.
- `settings.gradle` should lie in the root of a project.
> Run snippet_writer in build

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/Hamiltonian.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NUTS.java
Some of the code within the samplers is redundant as the `PosteriorSamplingAlgorithm` interface has default methods that provide the same functionality.
> Use interface defaults for PosteriorSamplingAlgorithms

- README.md
Not must-have, but this is to ensure similar convention to other improbable projects like https://github.com/improbable-eng/thanos (:
> Added slack button badge to Readme.

- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/GenericTensorVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/GenericVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/CPTVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/ConstantGenericVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/IfVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/MultiplexerVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/operators/binary/BinaryOpVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/operators/unary/UnaryOpVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/generic/probabilistic/discrete/CategoricalVertex.java
I've added 2 new abstract classes `GenericVertex` and `GenericTensorVertex`.
Just an idea I'm putting up to see what you think... some people may not like the idea of creating another abstract class, but personally I find it easier to reason about the hierarchy when it looks like this:
> tidy up the Vertex class hierarchy

- keanu-project/src/main/java/io/improbable/keanu/util/ProgressBar.java
In the case that samples are dropped, the progress bar showed two percentages after the dropping had occurred. This is due to the difference in the string length between `Dropping samples...` and `Sampling...` which meant the dropping samples percentage wasn't being cleared. I have fixed this by appending spaces to clear previous output when the previous output was longer. 
This is a bit hacky so open to other ideas. Tried using `\b` as a backspace but that didn't seem to work.
> Fix progress bar dual percentage displaying

- docs/_config.yml
- docs/_data/previous_versions.yml
- docs/release_notes.txt
- keanu-python/docs/conf.py
Set docs version of develop to 0.0.19.
Added a `release_notes.txt` file for people to populate with new features. I prefer this to Google docs as it's versioned and visible to users.
> Bump develop to 19 and add release journal

- keanu-python/build.gradle
The python docs weren't being generated as part of the build. This meant that changes to the Python API weren't reflected in the docs automatically.
> finalize build with making python docs

- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/SamplingAlgorithm.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/nuts/Leapfrog.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/nuts/NUTS.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/nuts/NUTSSampler.java
- keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/nuts/Stepsize.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/nuts/LeapfrogTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/nuts/NUTSTest.java
- keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/testcases/MCMCTestDistributions.java
A few fixes to our current NUTS implementation. It fixes:
1. Leapfrog was not leaping properly
1. The tree size and sum acceptance rate wasn't being tracked correctly
1. NUTS now checks to a network in a zero probability state before running inference
> Classic nuts fixes

- keanu-python/Pipfile
A new release in a package we use (yapf) with different behaviour caused the build to start failing on a previously good commits. This PR fixes the versions of packages we use, which will stop this issue happening again.
The downside is that we are no longer up to date with the latest releases in these packages. We should make sure to periodically check if there have been any new releases to these packages, and whether it will be beneficial to upgrade.
> fix versions in pipfile

- keanu-python/build.gradle
We use Python 3 so we should be using pip3 and python3 commands. It's not a guarantee that pip links through to pip3 on all systems so we should explicitly call the correct version. Specifically hitting this issue on Ubuntu 16.04 build agents.
>  Use pip3 and python3

- .gitattributes
- gradle/spotless.gradle
Currently when building on Windows, the `spotlessPython` step will pass the first time the code is run however on further runs it will fail due to formatting errors in the generated python files.
Spotless checks that the line endings are the ones that the user's OS uses (unless specified otherwise in gitattributes). For windows this is CRLF and for unix this LF. The files are currently being generated using LF line endings on all OS's.
We don't really need to run any formatting checks on the generated files so for the time being they can be ignored.
I was hitting this problem when running multiple times on a build agent. This fix stops this problem.
> Ignore generated python from spotless

- keanu-python/build.gradle
- keanu-python/nd4j/build.gradle
Currently running `./gradlew clean` doesn't delete the classpath in the python packages. This PR clears those directories on clean. This should give better guarantees when running `./gradlew clean build`
> Delete python classpath on clean

- ci/build_and_deploy.sh
Release script referenced the wrong location for the key file as this has recently changed.
> Fix key location to CI dir

- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DoubleVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/SliceVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ConcatenationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/MatrixInverseVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ReshapeVertexTest.java
- release_notes.md
Note that the reshape is not done at the tensor level, because that will interfere with auto diff.
The new behaviour of matrix multiply was copied from numpy's `matmul`.
> Support for vector-vector and matrix-vector product.

- keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/MultivariateGaussian.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShapeValidation.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/bool/BooleanTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/IntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/LogProbGraph.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/Differentiator.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/ConstantDoubleVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/AutoDiffBroadcast.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertex.java
- keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/MultivariateGaussianVertex.java
- keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensorTest.java
- keanu-project/src/test/java/io/improbable/keanu/util/io/JsonTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MatrixMultiplicationVertexTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/MultivariateGaussianTest.java
- keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/ProbabilisticDoubleTensorContract.java
- release_notes.md
This PR:
- The multivariate gaussian mu is a vector now. Doesn't need to be a matrix and in fact shouldn't be.
- Cleaned up the multivariate gaussian log prob graph to allow transpose() and remove the unnecessary slice.
- The ScalarDoubleTensor was not doing tensor multiply. This has been implemented and is needed for when the result of a matrix multiply is a (1,1)
- Forward mode auto-diff correct for broadcasting didn't work with (1,1) -> (2,2,2). This now works.
> Multivariate Gaussian cleanup

- keanu-project/src/main/java/io/improbable/keanu/templating/SequenceItem.java
- keanu-python/keanu/sequence.py
- keanu-python/tests/test_sequence.py
Exposes a `getContents()` method on `SequenceItem` which I have found useful for the purposes of debugging.
It allows a narrower view into the graph than `vertex.getConnectedGraph()` because it only shows vertices that have been explicitly added and only vertices from this sequence item.
This PR also adds the `get_last_item()` method to the python `Sequence` API to match the Java API
> Expose SequenceItem contents

- .buildkite/premerge.definition.yaml
- .buildkite/release-python.definition.yaml
Updating the pipeline definition to match the perms set in the BuildKite pipeline.
This was manually changed in the BK UI.  Please don't do that.
See [here](https://docs.improbable.io/internal/platform/product-groups/dev-workflow/buildkite/how-to-create-a-new-pipeline#update-a-pipeline) for the correct way to do this.
> Fix incorrect pipeline permissions
