keanu-project/build.gradle

Now using maven gradle plugin and signing plugin to publish keanu jar to Maven Central

Add signing of jar in order to publish to maven central

---

README.md

Simple update to the feature list from Dan Tang

Add kotlin and MAP in feature list in README

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/PowerVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/PowerVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcCosVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ArcSinVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CosVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/PowerVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SinVertexTest.java

To be able to raise a DoubleVertex to the power of another DoubleVertex.

Power Vertex - Accept Vertex as hyper parameter

---

keanu-docs/examples.md
keanu-examples/coalMiningDisasters/build.gradle
keanu-examples/coalMiningDisasters/src/main/java/com/example/coal/Model.java

Currently our coal mining example doesn't output anything. There's a test that asserts the switch year but there's nothing in the model main method that prints this. It's helpful for a new user to see the output when running the main method.
- Add model output and fix gradle application plugin to point to correct main class

Improve coal mining example output

---

keanu-project/build.gradle

Kick off development on next version.

Bump to 0.0.5-SNAPSHOT

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CeilVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/FloorVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CeilVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/FloorVertexTest.java

Floor and Ceil Operators for `DoubleVertex`

Floor & Ceil Operators

---

keanu-project/build.gradle

Step one of the release process

Remove snapshot in develop for 0.0.5 Release

---

keanu-project/build.gradle

Starting work on next version.

Bump version to 0.0.6-SNAPSHOT

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SigmoidVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SigmoidVertexTest.java

Adds https://en.wikipedia.org/wiki/Sigmoid_function

Add sigmoid vertex operation

---

keanu-project/build.gradle

Update version to 0.0.6

---

keanu-docs/getting-started.md
keanu-examples/starter/build.gradle
keanu-project/build.gradle

Set Keanu version to 0.0.7-SNAPSHOT

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/graphtraversal/TopologicalSort.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/graphtraversal/VertexValuePropagation.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/Hamiltonian.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/SimulatedAnnealing.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/sampling/RejectionSampler.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/FitnessFunction.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/FitnessFunctionWithGradient.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/GradientOptimizer.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/NonGradientOptimizer.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Beta.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Laplace.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/SmoothUniformDistribution.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Triangular.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Uniform.java
keanu-project/src/main/java/io/improbable/keanu/network/BayesNet.java
keanu-project/src/main/java/io/improbable/keanu/vertices/Vertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/LogProbGradient.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/DoubleUnaryOpLambda.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertex.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/HamiltonianTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/DualNumberPropagationTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/TestGraphGenerator.java
keanu-project/src/test/java/io/improbable/keanu/vertices/VertexValuePropagationTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/ArcTan2VertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/CeilVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/FloorVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/ProbabilisticDoubleContract.java

This PR addresses the need to cast to Vertex before passing network to MCMC algorithms.

Relax some generics where appropriate

---

README.md

Shamelessly add Improbable plug. We need more people...

Add hiring link to README

---

keanu-project/src/main/java/io/improbable/keanu/distributions/tensors/continuous/TensorLogistic.java
keanu-project/src/main/java/io/improbable/keanu/distributions/tensors/continuous/TensorTriangular.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbltensor/SimpleDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbltensor/probabilistic/TensorLogisticVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbltensor/probabilistic/TensorTriangularVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbltensor/probabilistic/TensorLogisticVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbltensor/probabilistic/TensorTriangularVertexTest.java

- Logistic Tensor
- Triangular Tensor

Logistic and Triangular Tensors

---

keanu-docs/getting-started.md
keanu-project/build.gradle

bump snapshot to 0.0.8

---

keanu-examples/starter/build.gradle
keanu-examples/starter/src/main/java/com/example/starter/Model.java

bump version to 0.0.7

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/tensor/TensorNUTS.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/tensormcmc/TensorNUTSTest.java

Tensor NUTS

---

keanu-examples/coalMiningDisasters/build.gradle
keanu-examples/coalMiningDisasters/src/main/java/com/example/coal/Data.java
keanu-examples/coalMiningDisasters/src/main/java/com/example/coal/Model.java
keanu-examples/coalMiningDisasters/src/test/java/com/example/coal/ModelTest.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgrtensor/IntegerTensorVertexSamples.java

Just some cleanup on the coal mining example. This converts it to use tensor vertices, which is a lot easier to read.

Convert coal mining example to use tensor vertices

---

keanu-project/src/main/java/io/improbable/keanu/distributions/tensors/continuous/TensorChiSquared.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbltensor/probabilistic/TensorChiSquaredVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbltensor/probabilistic/TensorChiSquaredVertexTest.java

Add tensor support for the Chi squared distribution.

Add Chi2 to double tensor vertices

---

keanu-docs/getting-started.md
keanu-examples/starter/build.gradle
keanu-examples/starter/src/main/java/com/example/starter/Model.java

Update starter project and set docs to point to 0.0.8

Starter project to use keanu 0.0.8

---

keanu-project/src/main/java/io/improbable/keanu/vertices/bool/probabilistic/Flip.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/bool/probabilistic/FlipVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/probabilistic/UniformIntVertexTest.java

Fixes some minor bugs discovered recently.

Fix uniform int range and sampling bug as well as flip sample shape bug

---

keanu-project/src/main/java/io/improbable/keanu/tensor/Tensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/bool/BooleanTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/generic/GenericTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/IntegerTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/unary/BoolReshapeVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ReshapeVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/operators/unary/IntegerReshapeVertex.java
keanu-project/src/test/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/tensor/generic/SimpleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/bool/BoolVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/unary/BoolReshapeVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ReshapeVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/IntegerVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/operators/unary/IntegerReshapeVertexTest.java

Reshape tensor for double, bool and integer.
Added a reshape to the Boolean Tensor. Didn't want to write my own reshape (edge cases etc...) so I've cast it to an Integer Tensor, done a ND4j reshape and then converted that back to a BooleanTensor.

Reshape Tensor

---

keanu-examples/starter/build.gradle
keanu-examples/starter/src/main/java/com/example/starter/Data.java

Use the newly released keanu 0.0.9 in the starter project.

Use 0.0.9 in starter project

---

keanu-examples/starter/src/main/java/com/example/starter/Model.java

Currently the starter project prints:
```
A is most probably io.improbable.keanu.tensor.dbl.ScalarDoubleTensor@67700764
B is most probably io.improbable.keanu.tensor.dbl.ScalarDoubleTensor@6a580400
```
It should print
```
A is most probably -0.16666666666628804
B is most probably 2.333333333333477
```

Update starter project to print values correctly

---

keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/bool/probabilistic/Flip.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/bool/probabilistic/FlipVertexTest.java

Very big bug that wasn't caught by our test somehow.

Fix bug in logProb of Flip

---

keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShapeValidation.java
keanu-project/src/main/java/io/improbable/keanu/vertices/bool/BoolVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/bool/nonprobabilistic/operators/unary/BoolPluckVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/multiple/ConcatenationVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/PluckVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/operators/unary/GenericPluckVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/IntegerVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/operators/unary/IntegerPluckVertex.java
keanu-project/src/test/java/io/improbable/keanu/tensor/generic/SimpleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/bool/BoolVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DoubleVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/PluckVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/IntegerVertexTest.java

Pluck a value from a tensor, this plucks the relevant auto diff too if it's a double.
I need this before I can do `if`. https://improbableio.atlassian.net/secure/RapidBoard.jspa?rapidView=377&modal=detail&selectedIssue=SOL-1976
I also tidied up the concat dual number method.

Pluck Vertex

---

keanu-project/src/main/java/io/improbable/keanu/util/csv/ColumnWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/RowWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/SampleWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/Writer.java

So people can actually use it....
Thanks Chris!

Make writer public

---

keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/test/java/io/improbable/keanu/vertices/DualNumberPropagationTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertexTest.java

Diffable If.
Currently only works for a constant predicate and with doubles.

Gradient Optimiser works with constant If

---

keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java

This PR creates a shorthand for ND4js linspace and arange

Add factory method for linspace and arange

---

.travis.yml

This simply gets us to the point where at least travis will run the tests.  Still trying to get everything working with sonarcloud, but thought we'd want to get this in ASAP.

Adding travis instruction to actually run the tests

---

keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Cauchy.java
keanu-project/src/main/java/io/improbable/keanu/distributions/dual/Diffs.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/CauchyVertex.java
keanu-project/src/test/java/io/improbable/keanu/distributions/gradient/Cauchy.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/CauchyVertexTest.java

Let ![codecogseqn 2](https://user-images.githubusercontent.com/13027838/44026865-61aa19ce-9eec-11e8-82d2-26d3792cd62c.gif) be location and ![codecogseqn 3](https://user-images.githubusercontent.com/13027838/44026873-67f781b8-9eec-11e8-9ad3-2d3b6769c90b.gif) scale.
- Sampling from quantile function (inverse CDF) of Cauchy distribution:
- Log probability function of Cauchy:
- Partial derivatives of log probability:
Source: [WolframAlpha](http://www.wolframalpha.com/input/?i=derivative+of+-ln(pi)-ln(s)-ln(1%2B((x-m)%2Fs)%5E2)) and [Wikipedia](https://en.wikipedia.org/wiki/Cauchy_distribution#Characteristic_function).

Add cauchy distribution and vertex

---

keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Beta.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/ChiSquared.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Dirichlet.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Gamma.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/InverseGamma.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/KeanuRandom.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/GammaVertex.java
keanu-project/src/test/java/io/improbable/keanu/distributions/gradient/Gamma.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/GammaVertexTest.java

Similar to Exponential, just assume location is 0.

Remove location parameter from Gamma

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/PosteriorSamplingAlgorithm.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/GaussianKDE.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Gamma.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/RowWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/WriteCsv.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java

🔥 
Check `Analyze/Inspect Code` to confirm.

Remove unused imports

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfGaussianVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/HalfGaussianVertexTest.java

Using same concepts as HalfCauchyVertex

Added HalfGaussianVertex and tests

---

keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensorTest.java

Fix Nd4j{Integer, Double}Tensor#greaterThanOrEqual behaving like greaterThan

---

keanu-project/src/main/java/io/improbable/keanu/tensor/TypedINDArrayFactory.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java

Use the factory methods to force these to be Double typed not Float

Use factory methods to enforce double buffer type for linspace and arange

---

keanu-project/src/main/java/io/improbable/keanu/distributions/Distribution.java
keanu-project/src/main/java/io/improbable/keanu/distributions/discrete/Categorical.java
keanu-project/src/main/java/io/improbable/keanu/vertices/generic/probabilistic/discrete/CategoricalVertex.java

In the future, we should support multiple scenarios for Categorical.

Categorical implements Distribution

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/GaussianKDE.java
keanu-project/src/main/java/io/improbable/keanu/distributions/continuous/Pareto.java
keanu-project/src/main/java/io/improbable/keanu/vertices/bool/BoolVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/ParetoVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/generic/probabilistic/discrete/CategoricalVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/IntegerVertex.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/variational/KDEApproximationTest.java
keanu-project/src/test/java/io/improbable/keanu/distributions/gradient/Pareto.java
keanu-project/src/test/java/io/improbable/keanu/vertices/bool/BoolVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/probabilistic/ParetoVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/IntegerVertexTest.java

A few minor changes from PRs that went in while I was on vacation. The only change that might be confusing is the bit where I removed the observe method on BoolVertex, IntegerVertex, and DoubleVertex as that method is inherited from the Vertex class.

Comment changes for PRs while I was gone

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/KLDivergence.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/QDistribution.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/variational/KLDivergenceTest.java

Equation:
<a href="https://www.codecogs.com/eqnedit.php?latex=D_{KL}(P||Q)&space;=&space;\sum_{i}&space;P(i)\log&space;\left(\frac{P(i)}{Q(i)}&space;\right&space;)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?D_{KL}(P||Q)&space;=&space;\sum_{i}&space;P(i)\log&space;\left(\frac{P(i)}{Q(i)}&space;\right&space;)" title="D_{KL}(P||Q) = \sum_{i} P(i)\log \left(\frac{P(i)}{Q(i)} \right )" /></a>
Requirements:
- Q can't have smaller support than P
- When P is 0, contribution to divergence is 0

Add KL divergence

---

keanu-docs/docs/vertices.md

Update docs based on new Vertex names

---

keanu-project/src/main/java/io/improbable/keanu/tensor/Tensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/DoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/generic/GenericTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/IntegerTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/ScalarIntegerTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/VertexId.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ReshapeVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TakeVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumberTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TakeVertexTest.java

- reverse autodiff for take
- setting a value in a tensor now returns the original tensor
- pull out a helpful method to `TensorShape`

Reverse autodiff - take

---

keanu-project/src/main/java/io/improbable/keanu/vertices/Vertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/VertexId.java
keanu-project/src/test/java/io/improbable/keanu/plating/Loop.java
keanu-project/src/test/java/io/improbable/keanu/plating/LoopTest.java

Example:
"Plate_1:xValue": ConstantDoubleVertex({
data = [0.0]
shape = [1, 1]
})

added Vertex#toString that shows label, class, value

---

keanu-project/src/main/java/io/improbable/keanu/vertices/VertexLabel.java
keanu-project/src/main/java/io/improbable/keanu/vertices/VertexLabelException.java
keanu-project/src/test/java/io/improbable/keanu/vertices/VertexLabelTest.java

This will be needed for Plates: every Vertex in the Plate will have a VertexLabel, but the names in a BayesNet need to be unique. So we will scope the VertexLabel with the ID of the Plate.

added the concept of a namespace (list of strings) to VertexLabel

---

keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/ScalarIntegerTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SumVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/DifferentiatorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumberTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SumVertexTest.java

This PR:
- Reverse Autodiff with Sum
- Bug fix for elementwise multiply when of is a scalar

Sum reverse autodiff

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertexTest.java

- If Vertex assumed you were performing it on a tensor of rank 2, this fix enables it to work for all ranks

Fix bug in double if vertex

---

keanu-project/src/main/java/io/improbable/keanu/network/grouping/ContinuousPoint.java
keanu-project/src/main/java/io/improbable/keanu/network/grouping/DiscretePoint.java
keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/generic/GenericTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/ScalarIntegerTensor.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/Writer.java
keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/CPTCondition.java
keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/ConditionalProbabilityTable.java
keanu-project/src/test/java/io/improbable/keanu/util/csv/pojo/bycolumn/CsvReaderByColumnTest.java

May expose internal representation by returning reference to mutable object
May expose internal representation by incorporating reference to mutable object

Fixed findbug errors about storing/returning references to arrays:

---

keanu-docs/getting-started.md

Upgrade keanu docs to 13

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastings.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/proposal/GaussianProposalDistribution.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastingsTest.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/proposal/GaussianProposalDistributionTest.java

I withdrew the PR for a MultivariateGaussian proposal distribution, and instead submitted this one for the (univariate) Gaussian.

added GaussianProposalDistribution

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/Differentiable.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MaxVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MinVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/If.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleIfVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MaxVertexTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/binary/MinVertexTest.java

- Fix forward mode auto-diff for IF
- Add IF shape checks on predicate / then / else
- Min max gradient by wrapping IF

Simplify forward if + min / max auto diff

---

keanu-project/src/main/java/io/improbable/keanu/tensor/INDArrayShim.java
keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShape.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/ScalarDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/Differentiator.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/DoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/DualNumber.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/PartialDerivatives.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/ReshapeVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SumVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/TakeVertex.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/diff/LogProbGradientCalculatorTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/unary/SumVertexTest.java

Extends SumVertex to allow summing over specific dimensions.

Sum over dimensions

---

keanu-project/src/main/java/io/improbable/keanu/tensor/TensorShapeValidation.java
keanu-project/src/main/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensor.java
keanu-project/src/test/java/io/improbable/keanu/tensor/bool/SimpleBooleanTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensorTest.java
keanu-project/src/test/java/io/improbable/keanu/tensor/intgr/Nd4jIntegerTensorTest.java

Added a new method in `TensorShapeValidation` and call it from each Tensor ctor so we catch these issues earlier.

check tensor rank >= 2 on construction

---

deployment/release.sh

So we can test out the automated release!

Add release script to master

---

keanu-project/build.gradle
keanu-project/src/main/java/io/improbable/keanu/model/MAPModelFitter.java
keanu-project/src/main/java/io/improbable/keanu/model/MaximumLikelihoodModelFitter.java
keanu-project/src/main/java/io/improbable/keanu/model/ModelGraph.java
keanu-project/src/main/java/io/improbable/keanu/model/regression/LinearRegressionGraph.java
keanu-project/src/main/java/io/improbable/keanu/model/regression/RegressionModel.java
keanu-project/src/main/java/io/improbable/keanu/model/regression/RegressionModelBuilder.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/probabilistic/LaplaceVertex.java
keanu-project/src/test/java/io/improbable/keanu/e2e/regression/LinearLassoRegressionTest.java
keanu-project/src/test/java/io/improbable/keanu/e2e/regression/LinearRegressionTestUtils.java
keanu-project/src/test/java/io/improbable/keanu/e2e/regression/LogisticRegressionTest.java
keanu-project/src/test/java/io/improbable/keanu/tensor/TensorMatchers.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/operators/TensorTestOperations.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/probabilistic/MultinomialVertexTest.java

One of the regression model tests used a lambda (scale) that meant it didn't get close enough to the expected intercept value. I've decreased the scale causing it to have a tighter constraint on the intercept. I've also removed my name from the maven pom.

Broken regression test

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/NetworkSamples.java
keanu-project/src/main/java/io/improbable/keanu/algorithms/mcmc/NetworkSamplesGenerator.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/NetworkSamplesTest.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/MetropolisHastingsTest.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/mcmc/NetworkSamplesGeneratorTest.java
keanu-project/src/test/java/io/improbable/keanu/e2e/regression/LinearLassoRegressionTest.java

Disallow negative sample dropping, non-positive down sample intervals and dropping more samples than requesting.

Check for invalid sampling arguments

---

codegen/build.gradle
codegen/src/main/java/io/improbable/keanu/codegen/python/VertexProcessor.java
codegen/src/main/resources/generated.py.ftl
keanu-python/examples/__init__.py
keanu-python/examples/coal_mining.py
keanu-python/examples/thermometers.py
keanu-python/keanu/__init__.py
keanu-python/keanu/algorithm/__init__.py
keanu-python/keanu/algorithm/optimization.py
keanu-python/keanu/algorithm/sampling.py
keanu-python/keanu/base.py
keanu-python/keanu/generated/__init__.py
keanu-python/keanu/keanu_random.py
keanu-python/keanu/net.py
keanu-python/keanu/vertex/__init__.py
keanu-python/keanu/vertex/base.py
keanu-python/keanu/vertex/const.py
keanu-python/keanu/vertex/generated.py
keanu-python/tests/test_base.py
keanu-python/tests/test_coal_mining.py
keanu-python/tests/test_const.py
keanu-python/tests/test_gradient_optimization.py
keanu-python/tests/test_keanu_random.py
keanu-python/tests/test_lorenz.py
keanu-python/tests/test_net.py
keanu-python/tests/test_non_gradient_optimization.py
keanu-python/tests/test_sampling.py
keanu-python/tests/test_tensor.py
keanu-python/tests/test_vertex.py
keanu-python/tests/test_vertex_operations.py

- `keanu.vertex` gives you all the generated vertices and `Const`.
- `keanu.algorithm` gives you the optimisers and `sample`.
I chose not to use these namespaces in our modules (i.e. explicitly use the directory namespace).

Put vertex related modules into vertex and sampling, optimizer into algorithm

---

keanu-python/Pipfile
keanu-python/examples/coal_mining.py
keanu-python/keanu/const.py
keanu-python/keanu/tensor.py
keanu-python/keanu/vartypes.py
keanu-python/keanu/vertex.py
keanu-python/setup.py
keanu-python/tests/test_const.py
keanu-python/tests/test_tensor.py

I put all acceptable types in `vartypes.py`.

Take pandas dataframe, series and numpy scalars as argument for vertices AND tensors

---

keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/CastDoubleVertex.java
keanu-project/src/main/java/io/improbable/keanu/vertices/dbl/nonprobabilistic/DoubleModelResultVertex.java

Remove unused imports that accidentally made it in Develop.

Apply spotless to remove unused imports.

---

keanu-python/LICENSE
keanu-python/MANIFEST.in
keanu-python/setup.py

Confirmed `LICENSE` included in our package in test pypi:
https://test.pypi.org/project/keanu/0.0.15.dev2/#files
After this PR is merged, I'll upload `0.0.15.dev1` with a license file.

Add license to setup.py.

---

docs/current_docs/inference-map.md
docs/doc_templates/inference-map.md

Fix broken link to thermometers example.

Correct link to thermometers example

---

keanu-python/build.gradle

Quick fix for bug: `https://github.com/pypa/pipenv/issues/3224`

Downgrade pipenv install due to bug from newest version.

---

README.md
keanu-python/build.gradle

because it needn't depend on auto-generating the python code

make formatApply run more quickly

---

docs/_config.yml
docs/_data/previous_versions.yml
docs/current_docs/future.md
docs/doc_templates/future.md
docs/doc_templates/inference-map.md
docs/legacy_docs/0_0_16/data-io.md
docs/legacy_docs/0_0_16/getting-started.md
docs/legacy_docs/0_0_16/inference-map.md
docs/legacy_docs/0_0_16/inference-posterior-sampling.md
docs/legacy_docs/0_0_16/installation.md
docs/legacy_docs/0_0_16/lorenz-example.md
docs/legacy_docs/0_0_16/overview.md
docs/legacy_docs/0_0_16/particle-filter.md
docs/legacy_docs/0_0_16/plates.md
docs/legacy_docs/0_0_16/simple-regression.md
docs/legacy_docs/0_0_16/tensors.md
docs/legacy_docs/0_0_16/thermometer-example.md
docs/legacy_docs/0_0_16/vertex-summary.md

- Fix broken links
- Save legacy 0.0.15 docs
- Upgrade docs to 0.0.16

docs upgrade to 0.0.16

---

docs/bin/snippet_writer.py
docs/current_docs/inference-map.md
docs/current_docs/inference-posterior-sampling.md
docs/current_docs/installation.md
docs/doc_templates/inference-map.md
docs/doc_templates/inference-posterior-sampling.md
docs/doc_templates/installation.md
docs/src/test/python/optimizer.py
docs/src/test/python/sampling.py

- Snippet writer now can examine a Python source directory as well as Java.
- Added Keanu install instructions.
- Added shiny doc code examples for Sampling/Optimizers.

[Python] Shiny docs for sampling/optimizers

---

codegen/build.gradle
keanu-examples/bayesianMethodsForHackers/src/main/java/com/examples/ABTesting.java
keanu-examples/bayesianMethodsForHackers/src/main/java/com/examples/ChallengerDisaster.java
keanu-examples/bayesianMethodsForHackers/src/main/java/com/examples/CheatingStudents.java
keanu-examples/bayesianMethodsForHackers/src/main/java/com/examples/TextMessaging.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/ABTestingTest.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/ChallengerDisasterTest.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/CheatingStudentsTest.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/TextMessagingTest.java
keanu-examples/coalMiningDisasters/build.gradle
keanu-examples/coalMiningDisasters/src/main/java/com/example/coal/Model.java
keanu-examples/coalMiningDisasters/src/test/java/com/example/coal/ModelTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/dbl/KeanuRandomTest.java
keanu-python/tests/test_coal_mining.py

Reduced the number of samples we take in the `keanu-examples` tests

made keanu-examples tests shorter

---

docs/_config.yml
docs/_data/previous_versions.yml
docs/legacy_docs/0_0_17/autocorrelation.md
docs/legacy_docs/0_0_17/data-io.md
docs/legacy_docs/0_0_17/future.md
docs/legacy_docs/0_0_17/getting-started.md
docs/legacy_docs/0_0_17/inference-map.md
docs/legacy_docs/0_0_17/inference-posterior-sampling.md
docs/legacy_docs/0_0_17/installation.md
docs/legacy_docs/0_0_17/lorenz-example.md
docs/legacy_docs/0_0_17/overview.md
docs/legacy_docs/0_0_17/particle-filter.md
docs/legacy_docs/0_0_17/plates.md
docs/legacy_docs/0_0_17/save-and-load.md
docs/legacy_docs/0_0_17/simple-regression.md
docs/legacy_docs/0_0_17/tensors.md
docs/legacy_docs/0_0_17/thermometer-example.md
docs/legacy_docs/0_0_17/vertex-summary.md

We've been freezing the docs version after doing a release meaning we always lag one behind. Let's set the next version to be the `next released version` now so that when we release it's set correctly

Freeze 17 and set next version to 18

---

docs/current_docs/lorenz-example.md
docs/doc_templates/lorenz-example.md
docs/src/test/python/lorenz.py

Added a Python example of Lorenz to the shiny docs.

Shiny python lorenz example

---

keanu-project/src/main/java/io/improbable/keanu/network/BayesianNetwork.java
keanu-project/src/main/java/io/improbable/keanu/vertices/VertexLabel.java
keanu-project/src/test/java/io/improbable/keanu/network/BayesianNetworkTest.java
keanu-project/src/test/java/io/improbable/keanu/vertices/VertexLabelTest.java

Add VertexLabel#isInNameSpace and BayesianNetwork#getVerticesInNamespace

---

keanu-project/src/main/java/io/improbable/keanu/vertices/generic/nonprobabilistic/ConditionalProbabilityTable.java
keanu-project/src/main/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/IntegerCPTVertex.java
keanu-project/src/test/java/io/improbable/keanu/vertices/intgr/nonprobabilistic/IntegerCPTVertexTest.java

Added an IntegerCPTVertex. This code is very similar to the DoubleCPTVertex.

Add IntegerCPTVertex

---

docs/src/test/python/Pipfile
docs/src/test/python/autocorrelation.py
docs/src/test/python/sampling.py

There had been an update in the API for sampling in Python. This PR updates the code which is used in the code snippets to use the new API.
Also added a Pipfile which  makes it easier to use the version of `keanu-python` from the repo instead of the system one when checking this code works. Eventually we will make sure this code runs as part of the build, but for the time being will add a note into the release process to ensure we check this code runs prior to release.

Update Python shiny docs snippets

---

docs/current_docs/autocorrelation.md
docs/current_docs/simple-regression.md
docs/src/test/python/test_autocorrelation.py
keanu-python/keanu/algorithm/sampling.py
keanu-python/tests/test_sampling.py
release_notes.md

Work done by Mike Tyson to change the indexing of the child column of samples to accept tuples and not strings.

tuple index in data frame

---

keanu-project/src/test/java/io/improbable/keanu/e2e/regression/RadonHierarchicalRegression.java

This runs for bleedin' ages - as it's not currently working as expected, let's lower the number of samples.

Lower number of samples

---

keanu-python/keanu/functional/__init__.py
keanu-python/keanu/functional/iterator.py
keanu-python/tests/test_iterator.py

A little something that I need for Plates.
Python iterators don't have a concept of `hasNext()` so I needed to implement that.

implemented Java Iterators in Python

---

deployment/release.sh

- Makes sure develop is up to date
- Moves the user to master before showing the latest tag

improve deploy script

---

keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/ABTestingTest.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/ChallengerDisasterTest.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/CheatingStudentsTest.java
keanu-examples/bayesianMethodsForHackers/src/test/java/com/examples/TextMessagingTest.java
keanu-examples/coalMiningDisasters/src/test/java/com/example/coal/ModelTest.java
keanu-project/src/main/java/io/improbable/keanu/vertices/VertexId.java
keanu-project/src/test/java/io/improbable/keanu/DeterministicRule.java
keanu-project/src/test/java/io/improbable/keanu/util/io/DotSaverTest.java
keanu-project/src/test/java/io/improbable/keanu/util/io/JsonTest.java
keanu-python/keanu/__init__.py
keanu-python/keanu/keanu_random.py
keanu-python/keanu/vertex/base.py
keanu-python/tests/conftest.py
keanu-python/tests/test_coal_mining.py
keanu-python/tests/test_gradient_optimization.py
keanu-python/tests/test_non_gradient_optimization.py
keanu-python/tests/test_sampling.py
keanu-python/tests/test_vertex.py

Python tests should now all automatically be deterministic (ie start with a known random seed and vertex ID values)

Deterministic Python Testing

---

keanu-project/src/main/java/io/improbable/keanu/algorithms/variational/optimizer/nongradient/BOBYQA.java
keanu-project/src/test/java/io/improbable/keanu/algorithms/variational/optimizer/nongradient/BOBYQATest.java

Better error message if trying to optimise for less than 2 dimensions

Error message for BOBYQA

---

docs/src/test/java/io/improbable/snippet/CsvOperations.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/ColumnWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/RowWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/SampleWriter.java
keanu-project/src/main/java/io/improbable/keanu/util/csv/Writer.java

To avoid out of memory
https://improbableio.atlassian.net/browse/SOL-3371

Stream samples

---

release_notes.md

Some 0.0.21 features were added under 0.0.20 so this fixes them. I also had forgotten to enter a note about ND4J so have also included that.

Fix up release notes

---

.buildkite/premerge.steps.yaml
.buildkite/release-python.steps.yaml

... so need to constrain, here.

ENG-890 will create multiple images per queue

---

keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/JVMDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/Nd4jDoubleTensor.java
keanu-project/src/main/java/io/improbable/keanu/tensor/dbl/TensorMulByMatrixMul.java

A refactor of the insane tensor mmul code.

Refactor tensor mmul code
